### ISSUE TITLE
Similar config, cognito federation problem

### ISSUE THREAD

**Issue by Thomazella** [timmytan18/ChickenTinder#1]
Hi

I have a similar project with similar AWS components and *cannot* get identities from a third party open id provider to work with AppSync. Would it be possible to share the shape (with no config values) of the `aws-exports.js` file with me? So I can check my configuration

thanks.

**Comment by timmytan18** [comment]
Hey,

Yeah my aws-exports.js looks like this:

{
    "aws_project_region": "",
    "aws_appsync_graphqlEndpoint": "",
    "aws_appsync_region": "",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "",
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "",
    "aws_user_pools_id": "",
    "aws_user_pools_web_client_id": "",
    "oauth": {
        "domain": "",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "",
        "redirectSignOut": "",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
}

There's also some configuration that has to be done in the Cognito console
to set up third party providers.

Hope this helps!

**Comment by Thomazella** [comment]
thanks man

**Comment by Thomazella** [comment]
For `redirectSignIn` and `redirectSignOut` what does the URL look like? I think it needs to be a deeplink into the app so something like `your-app-link://<not sure what goes here>` ?

**Comment by timmytan18** [comment]
Your domain value should be in your user pool under Domain name, should be something like appname621f211f-621f221f-dev.auth.us-east-1.amazoncognito.com, but when you push, aws-exports.js should auto update.

My redirectSignIn/Out looks something like
`"redirectSignIn": "exp://127.0.0.1:19000/--/,exp://192.983.1.345:19000/,exp://exp.host/@ttan18/Chicken+Tinder/,chickentinder://"`
where I have multiple URIs but I'm not that's necessary. 
I'm using Expo for my RN app so it handles linking with the Linking library. The part that comes after :// is dependent on what you're running the app on (device or simulator). The link that I have in my aws-exports is created from Linking.makeUrl(), which is the link that redirects back into the app after the third party log in.

My code looks like: 
`const expoScheme = "chickentinder://"
let redirectLink = Linking.makeUrl();
if (redirectLink.startsWith('exp://127')) {
    // handle simulator(localhost) and device(Lan)
    redirectLink = redirectLink + '/--/';
} else {
    if (redirectLink === expoScheme) {
    } else {
        // handle the expo client
        redirectLink = redirectLink + '/'
    }
}

awsconfig.oauth.redirectSignIn = redirectLink;
awsconfig.oauth.redirectSignOut = redirectLink;`

I think I used
[https://stackoverflow.com/questions/58420797/how-to-get-expo-static-deep-link-for-development](url) for help.

But also make sure that the links in the Cognito console match your aws-exports. I think I had issues getting it to update correctly.
